
"use client"
import './globals.css'
import { Inter } from 'next/font/google'

import Navbar from '@/app/components/Navbar/Navbar'
import Footer from '@/app/components/Footer/Footer'


import { AuthProvider } from './AuthContext'


const inter = Inter({ subsets: ['latin'] })

/* META DATA - it is important but will be ignored */

// export const metadata = {
//  title: 'Create Next App',
//  description: 'Generated by create next app',
// }

export default function RootLayout({
 children,
}: {
 children: React.ReactNode
}) {
 return (
  <html lang="en">

   <body className={inter.className + " " + "p-9"}>
    <AuthProvider>
     <Navbar />
     {children}
     <Footer />
    </AuthProvider>
   </body>
  </html>

 )
}
